services:
  web:
    build: .
    command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 backend_app.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - db

  db:
    image: keinos/sqlite3:latest
    volumes:
      - ./data:/data
    environment:
      - SQLITE_DATABASE=db.sqlite3